version: "3.9"

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    environment:
      MB_DB_FILE: /metabase.db
    ports:
      - "3000:3000"
    volumes:
      - ./.metabase:/metabase.db
      - ./data:/data:ro
